# Generated by Django 5.1.1 on 2025-02-15 18:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_option_question_topic_userquizattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizattempt',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
