# Generated by Django 5.1.1 on 2025-02-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userquizattempt_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizattempt',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
